@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.ridanisaurus.emendatusenigmatica.blocks;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;