@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.ridanisaurus.emendatusenigmatica.core.mixin;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;