#
# MIT License
#
# Copyright (c) 2024. Ridanisaurus
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.configuration-cache=true

## Environment Properties
# You can find the latest versions here: https://projects.neoforged.net/neoforged/neoforge
# The Minecraft version must agree with the Neo version to get a valid artifact
minecraft_version=1.21.1
# The Minecraft version range can use any release version of Minecraft as bounds.
# Snapshots, pre-releases, and release candidates are not guaranteed to sort properly
# as they do not follow standard versioning conventions.
minecraft_version_range=[1.21.1,1.21.2)
# The Neo version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.209
# The Neo version range can use any version of Neo as bounds
neo_version_range=[21.1.209,)
# The loader version range can only use the major version of FML as bounds
loader_version_range=[4,)

# Utilities and other mods
# URL: https://www.curseforge.com/minecraft/mc-mods/tool-kit/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
tool_kit_version=5521502
# URL: https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
architectury_version=5786327
# URL: https://www.curseforge.com/minecraft/mc-mods/world-stripper/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
world_stripper_version=5592921
# URL: https://www.curseforge.com/minecraft/mc-mods/jade/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
jade_version=6291517
# URL: https://www.curseforge.com/minecraft/mc-mods/the-undergarden/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
the_undergarden_version=5769852
# URL: https://www.curseforge.com/minecraft/mc-mods/kubejs/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
kubejs_version=5810100
# URL: https://www.curseforge.com/minecraft/mc-mods/rhino/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
rhino_version=6184623

# EMI
# URL: https://www.curseforge.com/minecraft/mc-mods/emi/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
emi_version=1.1.22

# Occultism
# URL: https://www.curseforge.com/minecraft/mc-mods/occultism/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
occultism_version=6940496
# URL: https://www.curseforge.com/minecraft/mc-mods/geckolib/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
geckolib_version=6920810
# URL: https://www.curseforge.com/minecraft/mc-mods/modonomicon/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
modonomicon_version=6839157
# URL: https://www.curseforge.com/minecraft/mc-mods/smartbrainlib/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
smartbrainlib_version=6762621
# URL: https://www.curseforge.com/minecraft/mc-mods/curios-continuation/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
curios_version=5888964

# Ars Nouveau
# URL: https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/all?page=1&pageSize=20&version=1.21.1.1&gameVersionTypeId=6
an_version=6954892

# Create
# URL: https://www.curseforge.com/minecraft/mc-mods/create/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
create_version=6641610

# Thermal
# URL: Didn't port yet >.>
thermal_expansion_version=null
# URL: Didn't port yet >.>
thermal_foundation_version=null
# URL: Didn't port yet >.>
cofh_core_version=null

# Mekanism
# URL: https://www.curseforge.com/minecraft/mc-mods/mekanism/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
mekanism_version=1.21.1-10.7.15.81

# Parchment. What else to say here!
neoForge.parchment.minecraftVersion=1.21.1
neoForge.parchment.mappingsVersion=2024.11.17

## Mod Properties
# Note: For readability, some of those were moved directly to neoforge.mods.toml!

# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod_id=emendatusenigmatica
# The mod version. See https://semver.org/
mod_version=1.21.1-2.2.0-beta-1
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=com.ridanisaurus