name: Build & Release

on:
  push:
    branches:
      - 1.18-Current

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip]')
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"
          cache: "gradle"
      - name: Build & release to curseforge
        env:
          NANITE_DEPLOY: ${{ secrets.NANITE_DEPLOY  }}
          CURSE_DEPLOY: ${{ secrets.CURSE_DEPLOY }}
        run: |
          chmod +x ./gradlew
          ./gradlew build publish curseforge --stacktrace --no-daemon
